
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Communa | Lorem Ipsum Dolor</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="libraries/font-awesome-4.6.3/css/font-awesome.min.css">

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Lato:400,100,300,700,900|Oswald:400,300,700' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <link href="libraries/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="css/mighty.css" rel="stylesheet">

  </head>

  <body>

    <?php include('modules/navigation.php'); ?>

    <!-- Mighty SubHeader Section -->
    <section class="mighty-subheader">
      <div class="container">
        <div class="row">
          <div class="text-center col-md-12 mighty-submsg">
            <h1>Terms &amp; Conditions</h1>
          </div>
        </div>
      </div>
    </section>

    <section class="">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">

            <h2>1.	GENERAL</h2>
            <p>Quantability Inc. owns and operates the Website at www.Communa.com (the “Website”). Your use of the Website or your participation in or use of any services or functions available on or through the Website (“Services”), including your participation as a community member in an online community or your participation in research opportunities, contests or promotions (sponsored by Communa or our clients), feedback or reviews is subject to these Terms of Use and our Privacy Policy (collectively the “Agreements”). Unless otherwise specified, all references to the “Website” include any software that Communa provides to you that allows you to access the Website from a mobile device (a “Mobile Application”).</p>
            <p>In the Agreements, Quantability Inc. and its affiliates are referred to collectively as “Communa”.</p>
            <p>Please note that any rewards or prizes offered or redeemed are supplied by Communa or our affiliated partners or accredited vendors and not by other commercial entities or brands presented or listed in communications or advertised.</p>
            <h2>2.	ACCEPTANCE OF TERMS</h2>
            <p>Please read all of the Agreements before accessing or using or registering for the Website or any Services, or accepting, uploading, submitting or downloading any information or content from or to the Website. Your access to, registration for and use of the Website or any Services constitutes acceptance of the Agreements. These Agreements may be updated and modified by us from time to time by posting revised Agreements on the Website. It is your responsibility to check to see whether any of the Agreements are updated. If you do not agree to be bound by the Agreements as they exist or as updated, then do not access or use the Website or Services. Continued use of the Website or Services after an Agreement is updated or modified is deemed to constitute acceptance of the updated or modified Agreement.</p>
            <p>These Agreements constitute a legal agreement between you and Communa, and shall apply to your access to and use of the Website or your use of or participation in Services even after that use or participation terminates.</p>
            <h2>3.	ELIGIBILITY</h2>
            <p>You represent and warrant that you are fully able and competent to enter into the Agreements and to abide by and comply with the terms of the Agreements. You must be legally capable of entering into binding contracts and must be the age of majority in your jurisdiction of residence before using or participating in Services or using the Website.</p>
            <h2>4.	ACCOUNT</h2>
            <p>You may register a user account (“Account”) on the Website to access and use certain Services or functions, including participating in an online community, research opportunities, contests or promotions.</p>
            <p>You may establish only one Account per person. If Communa discovers that you have registered for more than one Account, in addition to any other rights that Communa may have, Communa reserves the right to suspend or terminate any or all of your Accounts and terminate, withhold or revoke the awarding of any prizes, rewards or points earned or redeemed. You must provide Communa with accurate, complete, and updated information when establishing and updating your Account.</p>
            <p>You are responsible for maintaining the confidentiality of your login name, password and Account, and are responsible for all activities, and damages that occur under your Account regardless of whether you are the one actually using your account. Communa will not be liable for any loss or damage arising from the unauthorized use of your Account. However, you may be liable for Communa’s losses or the losses of others due to such unauthorized use.</p>
            <p>You will not permit or assist any other person to use your Account to use or participate in any Services. You agree to: (i) notify Communa immediately of any unauthorized use of your password or Account or any breach of security, (ii) ensure that you fully exit from your Account at the end of each session, and (iii) not use anyone else’s login name and password on the Website.</p>
            <h2>5.	PRIVACY</h2>
            <p>Communa will collect, use and disclose your personal information in accordance with its Privacy Policy, and you consent to those activities.</p>
            <p>You understand and agree that as a result of your registration of your Account and/or your use of and participation in the Services you may receive certain communications from Communa. You understand and agree that these communications are part of your registration, use or participation, and that, to the extent required by law, you may opt out of receiving these communications at any time by using the unsubscribe functionality. Following such an opt-out, Communa may still communicate with you via email to the extent permitted by applicable law.</p>
            <h2>6.	OTHER OBLIGATIONS</h2>
            <p>In consideration of your use or participation in research available on for or from the Website and/or a Community, you represent and warrant and agree to be bound by the following:</p>
            <ul>
              <li>You must be legally capable of entering into binding contracts and must be the age of majority in your jurisdiction of residence before using or participating in Services or using the Website.</li>
              <li>You agree to provide only accurate, current and complete information about yourself as prompted and maintain and promptly update such information to keep it accurate, current and complete.</li>
              <li>You will not use the Website or Services for any purpose that is unlawful or prohibited by the Agreements.</li>
              <li>In addition to, and without limiting, any other prohibitions set out in these Terms of Use, you may not do any of the following when accessing or using the Website or Services:</li>
              <ul>
                <li>use the Website or Services in any manner that could damage, disable, overburden, or impair the Website or Services or interfere with any other party's use and enjoyment of the Website or Services;</li>
                <li>use the Services to post, transmit, promote, or distribute illegal content, or to engage in or promote or encourage any illegal or fraudulent activity including hacking, cracking or distribution of counterfeit software, or identity theft;</li>
                <li>use the Services to promote your business or commercial venture (or a third party’s business or commercial venture);</li>
                <li>engage in harassment in any manner, including via e-mail, chat, or by use of obscene, offensive or abusive language (as determined by Communa in our sole discretion);</li>
                <li>impersonate others, including a Communa employee or representative, or other users of the Website or Services;</li>
                <li>reverse engineer, reverse compile, de-compile, hack, disable, disrupt, interfere with, disassemble, copy, decrypt, reassemble, supplement, translate, adapt or enhance the Website or Services or any services or Communa Content provided on or through the Services or try to defeat or bypass any of our encryption technologies or security measures or to circumvent any of our technological measures designed to control access to the Services or parts of the Services;</li>
                <li>use any robot, spider, site search/retrieval application, or other automated device or process to access, retrieve, scrape, or index any part of the Website, Services or Communa Content (as defined in section 15) available on or through the Services;</li>
                <li>upload to, distribute or otherwise publish any content that is defamatory, obscene, threatening, invasive of privacy or publicity rights, abusive, illegal, or otherwise objectionable, or which may constitute or encourage a criminal offence, violate the rights of any party or which may otherwise give rise to liability or violate any law; or</li>
                <li>upload any commercial content or solicit others to join or become members of any other online service or other organization.</li>
              </ul>
            </ul>
            <h2>7.	USER/RESEARCH CONTENT</h2>
            <p>The Website or Services may allow you to submit, post or upload videos, images, audio files, posting, tags, comments, messages and other information, including, but not limited to, profile information and communication with other users (“User Content”). You are entirely responsible for all User Content that you upload, post, and email or otherwise transmit via the Website or Services. You agree to post only User Content that is proper, non-abusive and lawful. In addition, but without limitation, you may not post content or engage in any other activity on the Website or within the Services that:</p>
            <ul>
              <li>defames, threatens, abuses or otherwise violates the legal rights of others;</li>
              <li>is harmful to children, profane, obscene, indecent or racially or ethnically offensive or that constitutes or may encourage a criminal offence;</li>
              <li>infringes another’s rights to intellectual property, publicity, or privacy;</li>
              <li>collects or stores personal information about other Website users;</li>
              <li>contains advertisements, promotions, commercial solicitations, contests or surveys (unless you have Communa’s written consent to do so);</li>
              <li>contains, transmits or disseminates spam, chain letters, or information deemed unacceptable or offensive to others.</li>
              <li>contains, transmits or disseminates viruses, corrupted files, or any other similar software or programs that may damage or adversely affect the operation of another’s computer, the Website, or any software, hardware or other related equipment;</li>
              <li>disrupts, damages or otherwise interferes with the Website or the networks or servers used by Communa or our affiliated businesses, partners or vendors;</li>
              <li>impersonates any person or entity or misrepresents your connection or affiliation with a person or entity; or</li>
              <li>constitutes illegal activity or may otherwise give rise to liability.</li>
            </ul>
            <p>You acknowledge that Communa may or may not pre-screen User Content, but that Communa and its designees have the right (but not the obligation) in their sole and absolute discretion to pre-screen, refuse, permanently delete, undelete, modify and/or move any User Content available via the Website or the Services, at any time without notice for any reason whatsoever. However, you acknowledge that Communa is not responsible for any User Content (whether yours or someone else’s). By providing the ability to view and distribute user-generated content, Communa is merely acting as a passive conduit for that distribution and is not undertaking any obligation or liability relating to any User Content.</p>
            <p>With respect to User Content you submit or otherwise make available on or to the Website or Services, you grant Communa an irrevocable, fully sub-licensable, perpetual, world-wide, royalty-free, non-exclusive license to use, distribute, reproduce, modify, adapt, publish, translate, publicly perform and publicly display such User Content (in whole or in part), and to incorporate such User Content into other works, in any format or medium now known or later developed, all without restriction and without compensation to you. You represent and warrant that you have all rights necessary to grant to Communa the license above and that none of your User Content violate any rights of third parties (including intellectual property rights or rights of publicity or privacy), or violate applicable law. You waive any moral rights in any User Content in favour of Communa. Without limiting the foregoing, if User Content includes any video and/or photographic images or pictures of you, you further agree that, without limitation, the license provided includes a grant of an unrestricted right and permission to use, re-use and publish the video and/or photographic images or pictures of you or provided by you, in you may be included intact or in part, composite or distorted in character or form (the “Images”), without restriction as to changes or transformations in conjunction with your own or a fictitious name, or reproduction thereof in color or otherwise, made through any and all media now or hereafter known for purposes of illustration, art, promotion, advertising, trade, sale or any other purpose whatsoever. Your permission given herein is hereby acknowledged to constitute written consent under applicable law,  if applicable. You also permit the use of any printed material in connection therewith. You hereby relinquish any right that you may have to examine or approve the use of the Images regardless of the form and type, the material that may be used in conjunction therewith or the use to which they may be applied. Further, you represent and warrant to Communa that: (i) all persons who appear in any Images have given you their express consent to submit the Images for unlimited, royalty-free use, exhibition and other exploitation in any manner and in any and all media, whether now existing or hereafter discovered, throughout the world, in perpetuity (and you agree to provide evidence of such permission in writing if requested by Communa in its sole and absolute discretion); (ii) there are no claims for payment of any kind, including, without limitation, for royalties or residuals; and (iii) no persons who appear in any Images has any approval or consultation rights or any rights of participation arising out of any use, exhibition or other exploitation of any Images.</p>
            <p>You are solely responsible for your interactions with other users of the Website or Services. Communa reserves the right, but has no obligation, to monitor disputes between you and other users.</p>
            <p>Except as provided in the Privacy Policy, Communa does not guarantee that User Content will be private, even if the User Content is in a password-protected area. Accordingly, you should not provide User Content that you want kept confidential or otherwise protected from others.</p>
            <p>Communa does not endorse any users or any User Content. Even to the extent that any of the Agreements requires you and other users to provide accurate information, Communa is under no obligation to attempt to confirm the identity of any user of the Website or Services or anything else about the user or the information the user is providing through the Services or the Website.</p>
            <h2>8.	SECURITY AND VIRUSES</h2>
            <p>Communa has implemented technology and security features to safeguard the privacy of your personal information from unauthorised access or improper use. We will continue to enhance our security procedures as new technology becomes available.</p>
            <p>While Communa makes every effort to ensure that your information is secure on Communa’s system, no data transmission over the Internet can be guaranteed to be 100 percent secure. As a result, Communa cannot guarantee the security of any information you transmit to Communa, and you do so at your own risk and your use of the Website and Services demonstrates your assumption of this risk.</p>
            <p>Communa has taken steps to ensure that the Website and Services are free of computer viruses and other harmful components. Nevertheless, you should install and maintain appropriate anti-virus and other protective software on the devices from which you access and use the Website and Services. Without limiting any other part of these Terms of Use, Communa disclaims all liability for any computer viruses or other harmful or destructive programs that you may download from the Website or Services.</p>
            <h2>9.	POINTS AND REWARDS</h2>
            <p>If you have a registered Account you may be able to earn membership points through various activities on or through the Website and Services and redeem those membership points to obtain various products or services. When redeeming membership points, your membership points account will be reduced by the specified number of membership required for the product or service being redeemed.<p>
            <p>Participation in the membership points program is a privilege that Communa can revoke in its sole discretion at any time and for any reason without compensation, including for your abuse of the membership point program or your breach of the Agreements. If Communa revokes your participation in the membership point program, your accrued membership points will be forfeited.<p>
            <p>Membership points are not redeemable for cash or any other form of credit and have no monetary value. Membership points cannot be refunded or exchanged for cash or any other tangible value. You have no ownership interest in your accrued membership points and accrued membership points do not constitute your property. Use of the word “earn” in relation to membership points means “collect” and does not infer that the membership points have any value. Membership points are personal to you and may not be purchased or sold and are not transferable. Membership points expire upon your death.<p>
            <p>Communa will provide on the Website a list of activities that generate membership points, and the amount of points required to obtain additional products or services. Communa may change this list at any time, and any revised list will be effective as of its posting on the Website.<p>
            <p>Communa reserves the right to change or discontinue this membership point program upon 30 days' notice posted on the Website. If that occurs, your right to receive membership points or and redeem membership points will end 30 days after we post the notice. Membership points not presented for redemption on or before such redemption end date cannot be redeemed.  All your membership points will be irrevocably and unconditionally forfeited if your Account is terminated or suspended for any reason, in Communa’s sole discretion, or if the Website or Services are terminated or discontinued.<p>
            <p>Communa is not responsible for any errors or omissions with regard to this membership points program. Communa is also not responsible for any lost or unauthorized use of membership points or for any redemption of membership points in the membership points program.<p>
            <p>The membership points program is void where prohibited by law.<p>
            <h2>10.	CONTESTS AND PROMOTIONS</h2>
            <p>Communa may from time to time hold promotional contests on or through the Website or Service (each a “Contest”). You do not have to participate in any Contest. Communa will set out separately the details of each Contest (the “Contest Details”), including the applicable contest period, the available prizes, the geographic scope, the method of entry, and any other relevant terms and conditions. The following terms and conditions will apply to each Contest, except that the Contest Details will take precedence if there is any inconsistency between the following terms and conditions and the Contest Details. The Contest Details and the following terms and conditions are collectively the “Contest Terms”.</p>
            <ul>
              <li>Each Contest is void where prohibited or restricted by law.</li>
              <li>No purchase is necessary to enter a Contest.</li>
              <li>To participate in a Contest you must:</li>
              <ul>
                <li>be a citizen or resident of the United States of America or Canada or United Kingdom (UK) or Australia or New Zealand and reside in a jurisdiction in which participation in any contest you choose to participate in is not prohibited by applicable law;</li>
                <li>not be (i) an employee, representative, mandatary, officer or director of Communa or any other Contest sponsor, or a contest judge; ; (ii) an immediate family member (defined as mother, father, brother, sister, son, daughter, or spouse, regardless of residence) of any such individual; or (iii) a person living in the same household of any such individual;</li>
              </ul>
            </ul>
            <p>Communa may disqualify you if you do not meet the Contest’s eligibility criteria, do not comply with or attempt to circumvent the Contest Terms, attempt to disrupt or undermine the Contest, or attempt to annoy, abuse, threaten or harass any other entrants or Communa representatives.</p>
            <p>To be eligible to enter any Contest or receive any prize, you may be required to provide Communa with additional documentation and/or information to verify your identity, and to provide proof that all eligibility requirements are met in Communa’s sole and absolute discretion. In the event of a dispute as to your identity or eligibility, Communa will, in its sole and absolute discretion, utilize certain information collected by Communa to assist in verifying your identity and/or eligibility.</p>
            <ul>
              <li>Winners will be selected as set out in the Contest Details. Communa will notify you by email, mail or telephone if you have been selected to receive a prize. To be declared a winner and eligible for the prize, you must be in compliance with the Contest Terms, and must sign and deliver to Communa (within any period that Communa specifies) a standard declaration and release form, which will include: a declaration of your compliance with the Contest Terms, an acceptance of the prize as awarded, a publicity release, a liability release, the correct answer to a skill-testing question, and any other documentation that Communa may require.
              If you cannot be contacted within 2 business days after the selection date, if you do not otherwise promptly respond to Communa’s communications, or if you do not sign and return any required documentation within the time periods that Communa specifies, you will forfeit the prize and your entries will be declared void.
              </li>
              <li>Each Contest’s prizes will be set out in the Contest Details. Prizes must be accepted as awarded (with no substitutions), and may not be sold, transferred or converted into cash.</li>
              <li>Communa may cancel, change, extend or suspend the Contest if for any reason Communa cannot run the Contest as planned. If that occurs, Communa may award the prize at random from among the eligible entries received up to the time of impairment, or award no prize.</li>
              <li>Rewards redeemed as cash or prizes awarded you hereby affirm that you have provided truthful responses to be included in a prize pool or contest or redemption of a reward and you are of legal or required age for participation.  It shall be a violation of these Terms of Use, entry or inclusion to a prize pool or contest or redemption of a cash incentive for providing false or untruthful responses.  Hence you will be excluded or invalidated which may result in removal from the community (including the loss of any points earned), contest or prize pool.</li>
              <li>Except where otherwise prohibited by law, participation in the contest constitutes a winner’s consent to Communa’s use of the winner’s name, hometown and photograph for promotional purposes without further notification, permission, payment or consideration.</li>
              <li>Communa is not responsible for and does not accept liability for any loss or damage resulting directly or indirectly from: (a) your participation in, or inability to participate in, a Contest; (b) any lost, delayed, misdirected, illegible, incomplete or undeliverable entries, or any delay or failure to transmit, process, receive or consider entries; (c) any technical failures affecting your participation in a Contest or the operation of a Contest; (d) any injury or damage to persons or property caused directly or indirectly from your participation in a Contest; (e) your receipt, use or redemption of any prize, or your inability to receive, use or redeem any prize; or (f) human error, theft, destruction or other factors beyond Communa’s control.</li>
              <li>By participating in a Contest you release and agreed to indemnify and hold harmless Communa and its employees, directors, officers, affiliates, agents, judges and advertising and promotional agencies from any damages, injuries, claims, causes of action, liability or losses (including actual legal fees and expenses), known or unknown, absolute or contingent, arising from or related to: (a) your failure to comply with any of the Contest Terms; (b) your participation in the Contest; (c) any misrepresentation you make under the Contest Terms or otherwise to Communa; or (d) your receipt, use or redemption of any prize, or your inability to receive, use or redeem any prize.</li>
              <li>For Québec residents.  If a Contest is operated in Quebec, Canada, any decision to be made by Communa may be subject to a ruling of the Régie des alcools des courses et des jeux du Québec. Any litigation respecting the conduct or organization of a publicity contest may be submitted to the Régie for a ruling. Any litigation respecting the awarding of a prize may be submitted to the Régie only for the purpose of helping the parties reach a settlement.</li>
              <li>Sections 12 (Indemnity), 13 (Disclaimer of Warranties), 14 (Limitation of Liability) and 17 (Miscellaneous) of these Terms of Use are part of and incorporated into the Contest Terms.</li>
            </ul>
            <h2>11.	TERMINATION AND EFFECT OF TERMINATION</h2>
            <p>In addition to any other legal or equitable remedy, Communa may, without prior notice, terminate or suspend any or all of your rights granted hereunder. In such event, you will immediately cease all access to and use of the Website and Services. Communa may revoke any password(s) and/or account identification issued to you and deny you access to and use of the Website or Services.</p>
            <p>Any such action shall not affect any rights and obligations arising prior thereto. All provisions of these Terms of Use, which by their nature should survive termination, shall survive termination, including, without limitation, intellectual property rights, disclaimers of warranty, indemnity and limitation of liability.</p>
            <h2>12.	INDEMNITY</h2>
            <p>You agree to indemnify, release and to hold harmless Communa, its parent company, subsidiaries, affiliates and agents, as well as the officers, directors, employees, shareholders and representatives of any of the foregoing entities (collectively, the “Released Parties”), from any and all liability, claims, losses, expenses, damages, costs (including actual legal expenses as billed) or actions of any kind whatsoever resulting directly or indirectly from any violation of these Terms of Use or any activity of yours relating to the Website or Services, including but not limited to injuries, damages, or losses to persons and property which may be sustained in connection with participation in the use of the Website or the use of or participation in Services, the receipt, ownership, use or misuse of any prize or reward redeemed or while preparing for, participating in and/or travelling to or from any Service-related activity, as well as any claims based on publicity rights, defamation, or invasion of privacy. Communa may, in its sole and absolute discretion, require you to execute a separate release of claims similar to the one listed above in this paragraph as a condition of being awarded any prize or reward/incentive or receiving any payout.</p>
            <h2>13.	DISCLAIMER OF WARRANTIES</h2>
            <p>You understand and agree that your use of the Website and Services is at your sole risk. The Website and Services, including, without limitation, all content, software, and functions made available on or accessed through or sent from the Website or Services, are provided on an “as is” and “as available” basis, without warranties of any kind, either express or implied, including, without limitation, implied warranties of merchantability, fitness for a particular purpose or non-infringement. Communa does not represent or warrant that functions contained in the Website or Services will be uninterrupted or error-free, that defects will be corrected, or that the Website, the Services or the servers that make them available are free of viruses or other harmful components. You acknowledge that Communa has no control over, and no duty to take any action regarding: which users gain access to or use the Website or participate in the Services; what effects the content on the Website or within the Services may have on you; how you may interpret or use the content on the Website or Services; or what actions you may take as a result of having been exposed to the content on the Website or Services. You release Communa from all liability for you having acquired or not acquired content through the Website and/or any of the research.</p>
            <p>You further acknowledge that your access to and use of the Website and the Services will not be free of interruptions, that the Website and the Services may contain bugs, errors, inaccuracies or other limitations, and that the Website and the Services may be unavailable from time to time.</p>
            <p>The Website or Services may contain or direct you to other websites or research containing information that some people may find offensive or inappropriate. Communa makes no representations concerning any content contained in or accessed through the Website or Services, and Communa will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the Website or Services.</p>
            <p>Communa does not warrant that your activities or use of the Website and/or the Services is lawful in any particular jurisdiction and, in any event, Communa specifically disclaims such warranties. You understand that by using any features of the Website and/or Services, you act at your own risk, and you represent and warrant that your activities are lawful in every jurisdiction where you access or use the Website and/or the Services.</p>
            <p>Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not fully apply to you.</p>
            <h2>14.	LIMITATION OF LIABILITY</h2>
            <p>You understand and agree that Communa limits its liability in connection with your use of the Website and/or use of or participation in the Services as set forth below: Except as limited by applicable law, under no circumstances shall Communa, its parents, subsidiaries, or affiliates, or the directors, officers, employees, or other representatives of each of them (collectively, the “Company Entities and Individuals”), be liable to you for any loss or damages of any kind (including, without limitation, for any special, direct, indirect, incidental, exemplary, economic, punitive, or consequential damages or loss of profits) that are directly or indirectly related to (1) the Website, the Services, or your User Content; (2) the use of, inability to use, or performance of the Website and/or Services; (3) any action taken in connection with an investigation by Communa or law enforcement authorities regarding your use of the Website and/or Services; (4) any action taken in connection with copyright owners; (5) any harm to your computer, hardware, computer software or other equipment or technology; or (6) any errors or omissions in the Website’s or Services’ technical operation, even if foreseeable or even if the Company Entities and Individuals have been advised of the possibility of such damages whether in an action of contract, negligence, strict liability tort (including, without limitation, whether caused in whole or in part by negligence, acts of God, telecommunications failure, or theft or in destruction of the Website, research or data). In no event will the Company Entities and Individuals by liable to you or anyone else for loss or injury. To the fullest extent permitted by applicable laws, you release the Company Entities and Individuals from all claims, actions, liabilities and damages of any kind relating to or arising from your access to and use of (or your inability to access and use) the Website and the Services. To the maximum extent permitted by applicable law, in no event shall the Company Entities and Individuals total liability to you for all damages, losses or causes of action exceed one hundred dollars ($100).</p>
            <p>You understand and agree that in the event you incur any damages, losses or injuries that arise out of Communa’s acts or omissions, the damages, if any, caused to you are not irreparable or sufficient to entitle you to an injunction preventing any exploitation of any website or other property owned or controlled by Communa and/or its parents, subsidiaries, and/or affiliates or your User Content, and you will have no rights to enjoin or restrain the development, production, distribution, advertising, exhibition or exploitation of the Website, Services or other property or your User Content or any and all activities or actions related thereto. By accessing the Website and/or sServices, you understand that you may be waiving rights with respect to claims that are at this time unknown or unsuspected. Accordingly, you agree to waive the benefit of any law that otherwise might limit your waiver of such claims.</p>
            <p>Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.</p>
            <h2>15.	INTELLECTUAL PROPERTY RIGHTS</h2>
            <p>All title, ownership and intellectual property rights in and to the Website and/or Services, including, without limitation, the text, software, scripts, graphics, photos, sounds, music, videos, interactive features and the like and the trademarks, service marks and logos contained therein (collectively “Communa Content”) are owned by or licensed to Communa. Communa Content is provided to you “as is”, “where is” and “with all faults” for your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of Communa. You do not acquire ownership rights to any such Communa Content by accessing or using the Website or Services, and our posting of that Communa Content is not a waiver of any right in or to that Communa Content. You agree not to circumvent, disable or otherwise interfere with security related features of the Website or Services features that prevent or restrict use or copying of any content on the Website and/or research or enforce limitations on use of such content.</p>
            <p>Notice and procedure for copyright infringement claim</p>
            <p>Communa takes claims of copyright infringement seriously. Communa will respond to notices of alleged copyright infringement that comply with applicable law. If you believe any materials accessible on, from, or through the Website or the Services infringe your copyright, you may request removal of those materials (or access to them) from the Website by submitting written notification to the Communa Copyright Agent (designated below). The written notice (the “DMCA Notice”) must include substantially the following:</p>
            <ul>
              <li>your physical or electronic signature.</li>
              <li>identification of the copyrighted work you believe to have been infringed or, if the claim involves multiple works, a representative list of such works.</li>
              <li>the date and time of the commission of the claimed infringement.</li>
              <li>a description of your interests or rights in or to the work claimed to have been infringed.</li>
              <li>identification of the material you believe to be infringing in a sufficiently precise manner to allow us to locate that material.</li>
              <li>adequate information by which Communa can contact you (including your name, postal address, telephone number and, if available, email address).</li>
              <li>a statement that you have a good faith belief that use of the copyrighted material is not authorized by the copyright owner, its agent or the law.</li>
              <li>a statement that the information in the written notice is accurate.</li>
              <li>a statement, under penalty of perjury, that you are authorized to act on behalf of the copyright owner.</li>
            </ul>
            Communa’s copyright agent can be reached in the following ways:
            <p>Mail:<br/>
            1 First Canadian Place, Suite 3400<br/>
            Toronto, ON<br/>
            M5X 1A4<br/>
            Email: support@Communa.com<br/>
            It is Communa’s policy in appropriate circumstances to disable and/or terminate the accounts of users who are repeat copyright infringers.</p>
            <h2>16.	MOBILE APPLICATION EXPORT REGULATION AND RELATED COMPLIANCE</h2>
            <p>Communa makes or may make available a Mobile Application to access the Website and Services via a mobile device. To use any Mobile Application you must have a mobile device that is compatible with the mobile service. Communa does not warrant that any Mobile Application will be compatible with your mobile device. Communa hereby grants to you a non-exclusive, non-transferable, revocable license to use an object code copy of the Mobile Application for one registered account on one mobile device owned or leased solely by you, for your personal use.</p>
            <p>Any Mobile Application may be subject to export control laws, including, without limitation, the U.S. Export Administration Act and its associated regulations. You shall not, directly or indirectly, export, re-export, or release any Mobile Application to, or make any Mobile Application accessible from, any jurisdiction or country to which export, re-export or release is prohibited by law, rule, or regulation. You shall comply with all applicable law and complete all required undertakings (including obtaining any necessary export license or other governmental approval), prior to exporting, re-exporting, releasing, or otherwise making any Mobile Application available outside the United States of America or Canada.</p>
            <p>You represent and warrant that you are not located in a country subject to an embargo from the U.S. or Canadian governments, or a country that the U.S. or Canadian government has designated a “terrorist supporting” country.</p>
            <p>You represent and warrant that you are not listed on any U.S. or Canadian government list of prohibited or restricted parties.</p>
            <h3>MOBILE CARRIER CHARGES</h3>
            <p>You acknowledge and agree that the use of a Mobile Application and/or use of or participation in Services may cause you to incur SMS and data charges from your mobile phone carrier. You agree that you shall be fully responsible for such charges and shall hold all Company Entities and Individuals harmless for such charges.
            <h3>MOBILE APPLICATION USE AND DOWNLOADS FOR APPLE AND ANDROID DEVICES.</h3>
            <p>To the extent you download a Mobile Application through the Apple App Store® or iTunes® or use the Mobile Application on an Apple®-branded product, including, without limitation, an Apple Watch®, Apple TV®, iPhone®, iPod-touch®, or iPad®, the following terms and conditions apply notwithstanding any contrary provisions in the Agreements:</p>
            <p>(a) You and Communa agree and acknowledge that the Agreements are by and between you and Communa and not with Apple.</p>
            <p>(b) You will only use the Mobile Application in compliance with the “Usage Rules” set forth in the Apple App Store Terms of Service.</p>
            <p>(c) You and Communa agree and acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the Mobile Application.</p>
            <p>(d) To the extent any warranty cannot be effectively disclaimed pursuant to Section 13or otherwise, and without otherwise limiting such disclaimer, Communa is solely responsible for any product warranties, express or implied, with respect to the Mobile Application. To the extent any warranty does so apply, you may notify Apple, and Apple will refund the purchase price for the Mobile Application, and that, to the maximum extent permitted by all applicable local, state, federal and international, law, rules, regulation, or orders, Apple will have no other warranty obligation whatsoever with respect to the Mobile Application, any other claims, losses, liabilities, damages, costs, or expenses attributable to any failure of the Mobile Application to conform to any applicable warranty.</p>
            <p>(e) Without otherwise prejudicing the limitations, disclaimers, and rights set forth in the Agreements that benefit Communa, including, without limitation, those set forth in Sections 12, 13 and 14=, Communa, and not Apple, shall be responsible for any indemnification claims brought by you or any third party relating to the Mobile Application, your possession and/or use of the Mobile Application, including, but not limited to, (i) product liability claims; (ii) any claim that the Mobile Application fails to conform to any requirement under applicable law; and (iii) claims arising under consumer protection or similar applicable law.</p>
            <p>(f) Without otherwise prejudicing the limitations, disclaimers and rights set forth in the Agreements that benefit Communa, including, without limitation, those set forth in Sections 12, 13 and 14, in the event of any third-party claim that the Mobile Application or your possession and use of the Mobile Application infringes that third party’s intellectual property rights, Communa, not Apple, will be solely responsible for the investigation, defense, settlement, and discharge of any such intellectual property infringement claim.</p>
            <p>(g) Notwithstanding Section 17(e), you and Communa acknowledge and agree that Apple, and Apple’s subsidiaries, are third-party beneficiaries of the Agreements, and that, upon your acceptance of the terms and conditions of the Agreements, Apple has the right (and will be deemed to have accepted the right) to enforce the Agreements against you as a third-party beneficiary hereof.</p>
            <p>The following additional terms and conditions apply with respect to any Mobile Application that Communa provides to you designed for use on an Android-powered mobile device:</p>
            <p>(a) You acknowledge that these Terms are between you and Communa only, and not with Google, Inc. (“Google”).</p>
            <p>(b) Your use of the Mobile Application must comply with Google’s then-current Google Play Terms of Service.</p>
            <p>(c) Google is only a provider of the online market where you obtained the Mobile Application. Communa, and not Google, is solely responsible for the Mobile Application and the services and content available thereon.  Google has no obligation or liability to you with respect to the Mobile Application or these Terms.</p>
            <p>(d) You acknowledge and agree that Google is a third-party beneficiary to the Terms as they relate to the Mobile Application.</p>
            <h2>17.	MISCELLANEOUS</h2>
            <p>(a)	Governing Law. Except where prohibited by law, these Terms of Use, your access to and use of the Website, and any claims made against Communa or its directors, officers, employees and representatives, arising out of such access and use or otherwise, shall be governed by and construed in accordance with the laws of the Province of Ontario and the laws of Canada applicable therein, without giving regard to its conflict of laws principles.</p>
            <p>(b)	Arbitration Except where prohibited by law, any and all disputes, claims or controversies arising out of or relating to the Agreements, the breach thereof, or any use of the Website and/or the Services (“Claims”), except for claims filed in a small claims court that proceed on an individual (non-class, non-representative) basis, shall be settled by binding arbitration before and under the auspices of one of the following centers, to be agreed upon by you and Communa: Roundtable Mediation & Arbitration Services, Aptus Conflict Solutions Inc., and Ottawa Dispute Resolution Group (the “Arbitration Center”) in accordance with its International Commercial Arbitration Rules</p>
            <p>In agreeing to arbitrate all Claims, you and Communa waive all rights to a trial by jury in any action or proceeding involving any Claim. Arbitration will take place in Toronto, Ontario, and you and Communa agree to submit to the personal jurisdiction of any court in Toronto, Ontario, in order to compel arbitration, to stay proceedings pending arbitration, or to confirm, modify, vacate or enter judgment on the award entered by the arbitrator.</p>
            <p>The parties further agree that, except where prohibited by law, any arbitration shall be conducted in their individual capacities only and not as a class action or other representative action, and the parties expressly waive their right to file a class action or seek relief on a class basis. You and Communa agree that each may bring claims against the other only in your or its individual capacity and not as a plaintiff or class member in any purported, class or representative proceeding. If any court or arbitrator determines that the class action waiver set forth in this paragraph is void or unenforceable for any reason or that an arbitration can proceed on a class basis, then the arbitration provision set forth above shall be deemed null and void in its entirety and the parties shall be deemed to have not agreed to arbitrate disputes.</p>
            <p>Notwithstanding the parties’ decision to resolve all disputes through arbitration, either party may bring an action in the courts in the Province of Ontario or the Federal Court of Canada to protect its intellectual property rights (“intellectual property rights” means patents, copyrights, moral rights, trademarks, and trade secrets, but not privacy or publicity rights). Either party may also seek relief in a small claims court for disputes or claims within the scope of that court’s jurisdiction.</p>
            <p>(c)	Linking. Any sites that are linked to from the Website or Services are not under Communa’s control, and you access them at your own risk. Communa does not assume any responsibility or liability for these linked sites or their contents. Communa provides all such links for your convenience only; they are not an endorsement or referral by Communa.</p>
            <p>If you wish to provide a link to the Website from your own web site, you may only link to the home page at www.communa.com.  You may not use any of Communa’s icons or logos on your web site without Communa’s prior written approval, and you may not use the link to suggest that Communa sponsors, endorses, approves of or is affiliated with you or your web site.</p>
            <p>(d)	Modifications. Communa may add new features to the Website or Services, remove existing features from the Website or Services, or otherwise modify the Website or Services (including their functionality, “look-and-feel”, universal resource locators and software components), all without notice to you.</p>
            <p>(e)	No Third Party Beneficiaries. Nothing in the Terms of Use shall create or confer any rights or other benefits in favor of any third parties except as specifically provided herein.</p>
            <p>(f)	No Agency Relationship. Nothing in the Terms of Use shall create or be deemed to create a partnership, agency, trust arrangement, fiduciary relationship or joint venture between you and Communa.</p>
            <p>(g)	Other Associations. Your participation, visitation or engagement with Communa is not for professional purposes benefiting you or any member of your family or party you are personally or professionally affiliated with.</p>
            <p>(h)	Waiver; Severability of Terms. If a court of competent jurisdiction deems any provision of these Terms of Use invalid, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Use, which shall remain in full force and effect. No waiver of any term of these Terms of Use shall be deemed a further or continuing waiver of such term or any other term, and Communa’s failure to assert any right or provision under these Terms of Use shall not constitute a waiver of such right or provision.</p>
            <p>(i)	Other Agreements. If there is any conflict between these Terms of Use and any other agreement between you and Communa, the latter agreements will prevail.</p>
            <p>(j)	Force majeure. The failure of Communa to comply with any provision of these Terms of Use due to an act of God, hurricane, war, fire, riot, earthquake, terrorism, act of public enemies, actions of governmental authorities outside of the control of Communa (excepting compliance with applicable codes and regulations) or other force majeure event will not be considered a breach of these Terms of Use, and Communa’s performance is deemed to be suspended for the period that the force majeure event continues.</p>
            <p>(k)	Headings. The section headings and sub-headings are contained in these Terms of Use for convenience only and have no legal or contractual effect.</p>
            <p>(l)	Language. The parties have expressly agreed that this agreement and also ancillary agreements, documents or notices related thereto be drafted solely only in English. Les parties aux présentes ont expressément convenus que cet accord et tout autre convention, documents soit rédigé en anglais seulement.</p>






























          </div>
        </div>
      </div>
    </section>

    <?php include('modules/footer.php'); ?>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="libraries/bootstrap/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
